### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by fogfish** [drySeaWind/geospatial#1]
Unfortunately, build fails with following errors

```
[ERROR] Errors:
[ERROR] com.iobionical.service.dao.FeatureDAOTest.initializationError(com.iobionical.service.dao.FeatureDAOTest)
[ERROR]   Run 1: FeatureDAOTest.initializationError »  Method testCreateTable should have no pa...
[ERROR]   Run 2: FeatureDAOTest.initializationError »  Method testFetchData should have no para...
[ERROR]   Run 3: FeatureDAOTest.initializationError »  Method testRowInsertCase should have no ...
[INFO]
[ERROR]   DataUploaderServletTest.initializationError »  Method isAllFunctionsInvoked sh...
[ERROR]   GeoSpatialServiceTest.initializationError »  Method testGetTrunksInArea should...
[INFO]
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0
```

It might be due to Java 9
```
java --version
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by fogfish** [comment]
JDK version is exactly the issue.

**Comment by svolotin** [comment]
Hi, yes it is becouse of JDK9. From JDK 9 on dynamic loading of agents is no allowed.
          <plugin> 
                <artifactId>maven-surefire-plugin</artifactId> 
                <version>2.22.0</version> 
                <configuration> 
                    <argLine>-Djdk.attach.allowAttachSelf</argLine> 
                </configuration> 
            </plugin>
https://www.linkedin.com/pulse/moving-java-10-sami-volotinen/ (in the end of the story)

JKD9 was mainly skipped by the industry and JDK11 seems to be the version which is offered LTS support by many vendors. This repo was developed to use JDK8 since container is running AdoptOpenJDK8 and they are promising LTS support. I can commit alternative version for other JDK's if needed (9?, 11?)
